# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Honeybearhoneypot < Formula
  desc "Whimsical SSH honeypot with a Fyne GUI"
  homepage "https://honeybear.hydrox.fun"
  version "1.3.2"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikeflynn/honeybearhoneypot/releases/download/v1.3.2/honeybearhoneypot_darwin_amd64.tar.gz"
      sha256 "72d249ac00d98bc3ff1026d7d1d2ef613f432a3596cbfbf1b373138c3ca5d389"

      def install
        bin.install "honeybearhoneypot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikeflynn/honeybearhoneypot/releases/download/v1.3.2/honeybearhoneypot_darwin_arm64.tar.gz"
      sha256 "e8796e4c3e69f467a9d1bcffc31e127de0e48b96c200a61abb33975f7d2d6864"

      def install
        bin.install "honeybearhoneypot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikeflynn/honeybearhoneypot/releases/download/v1.3.2/honeybearhoneypot_linux_amd64.tar.gz"
      sha256 "315e6129cbd0ac09d76707f8d38b62f253a18c711dcd9bfcee0ed3165d3fe62d"
      def install
        bin.install "honeybearhoneypot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikeflynn/honeybearhoneypot/releases/download/v1.3.2/honeybearhoneypot_linux_arm64.tar.gz"
      sha256 "c6325f0a6657bac3ab1cae5ee03ccd344a52b42ee0e228f1c617dce95a361262"
      def install
        bin.install "honeybearhoneypot"
      end
    end
  end
end
